services:
  - type: web
    name: verizon-home-internet
    runtime: docker
    repo: https://github.com/scopeoutteam/verizon-home-internet-app
    branch: main
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 3000
